/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as WorkRouteImport } from './routes/work'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioMediaRouteImport } from './routes/studio/media'
import { Route as StudioNewsletterRouteImport } from './routes/studio/newsletter'
import { Route as StudioSeoRouteImport } from './routes/studio/seo'
import { Route as StudioSettingsRouteImport } from './routes/studio/settings'
import { Route as StudioTopicsRouteImport } from './routes/studio/topics'
import { Route as TopicsSlugRouteImport } from './routes/topics/$slug'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StudioPostsIndexRouteImport } from './routes/studio/posts/index'
import { Route as StudioPostsIdRouteImport } from './routes/studio/posts/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioMediaRoute = StudioMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioNewsletterRoute = StudioNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioSeoRoute = StudioSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioTopicsRoute = StudioTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => StudioRouteRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPostsIndexRoute = StudioPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioPostsIdRoute = StudioPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => StudioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/work': typeof WorkRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/newsletter': typeof StudioNewsletterRoute
  '/studio/seo': typeof StudioSeoRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/topics': typeof StudioTopicsRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/studio/': typeof StudioIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/posts/$id': typeof StudioPostsIdRoute
  '/studio/posts/': typeof StudioPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/work': typeof WorkRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/newsletter': typeof StudioNewsletterRoute
  '/studio/seo': typeof StudioSeoRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/topics': typeof StudioTopicsRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/studio': typeof StudioIndexRoute
  '/writing': typeof WritingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/posts/$id': typeof StudioPostsIdRoute
  '/studio/posts': typeof StudioPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/work': typeof WorkRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/newsletter': typeof StudioNewsletterRoute
  '/studio/seo': typeof StudioSeoRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/topics': typeof StudioTopicsRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/studio/': typeof StudioIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/posts/$id': typeof StudioPostsIdRoute
  '/studio/posts/': typeof StudioPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/about'
    | '/login'
    | '/newsletter'
    | '/rss.xml'
    | '/work'
    | '/studio/media'
    | '/studio/newsletter'
    | '/studio/seo'
    | '/studio/settings'
    | '/studio/topics'
    | '/topics/$slug'
    | '/writing/$slug'
    | '/studio/'
    | '/writing/'
    | '/api/auth/$'
    | '/studio/posts/$id'
    | '/studio/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/newsletter'
    | '/rss.xml'
    | '/work'
    | '/studio/media'
    | '/studio/newsletter'
    | '/studio/seo'
    | '/studio/settings'
    | '/studio/topics'
    | '/topics/$slug'
    | '/writing/$slug'
    | '/studio'
    | '/writing'
    | '/api/auth/$'
    | '/studio/posts/$id'
    | '/studio/posts'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/about'
    | '/login'
    | '/newsletter'
    | '/rss.xml'
    | '/work'
    | '/studio/media'
    | '/studio/newsletter'
    | '/studio/seo'
    | '/studio/settings'
    | '/studio/topics'
    | '/topics/$slug'
    | '/writing/$slug'
    | '/studio/'
    | '/writing/'
    | '/api/auth/$'
    | '/studio/posts/$id'
    | '/studio/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  WorkRoute: typeof WorkRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/media': {
      id: '/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof StudioMediaRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/newsletter': {
      id: '/studio/newsletter'
      path: '/newsletter'
      fullPath: '/studio/newsletter'
      preLoaderRoute: typeof StudioNewsletterRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/seo': {
      id: '/studio/seo'
      path: '/seo'
      fullPath: '/studio/seo'
      preLoaderRoute: typeof StudioSeoRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/topics': {
      id: '/studio/topics'
      path: '/topics'
      fullPath: '/studio/topics'
      preLoaderRoute: typeof StudioTopicsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/posts/': {
      id: '/studio/posts/'
      path: '/posts'
      fullPath: '/studio/posts/'
      preLoaderRoute: typeof StudioPostsIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/posts/$id': {
      id: '/studio/posts/$id'
      path: '/posts/$id'
      fullPath: '/studio/posts/$id'
      preLoaderRoute: typeof StudioPostsIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface StudioRouteRouteChildren {
  StudioMediaRoute: typeof StudioMediaRoute
  StudioNewsletterRoute: typeof StudioNewsletterRoute
  StudioSeoRoute: typeof StudioSeoRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioTopicsRoute: typeof StudioTopicsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioPostsIdRoute: typeof StudioPostsIdRoute
  StudioPostsIndexRoute: typeof StudioPostsIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioMediaRoute: StudioMediaRoute,
  StudioNewsletterRoute: StudioNewsletterRoute,
  StudioSeoRoute: StudioSeoRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioTopicsRoute: StudioTopicsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioPostsIdRoute: StudioPostsIdRoute,
  StudioPostsIndexRoute: StudioPostsIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  WorkRoute: WorkRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
